// Password
export const PASSWORD_REQUEST = "PASSWORD_REQUEST";
export const PASSWORD_SUCCESS = "PASSWORD_SUCCESS";
export const PASSWORD_FAILED = "PASSWORD_FAILED";

export const EDIT_PASSWORD_REQUEST = "EDIT_PASSWORD_REQUEST";
export const EDIT_PASSWORD_SUCCESS = "EDIT_PASSWORD_SUCCESS";
export const EDIT_PASSWORD_FAILED = "EDIT_PASSWORD_FAILED";

export const DELETE_PASSWORD_REQUEST = "DELETE_PASSWORD_REQUEST";
export const DELETE_PASSWORD_SUCCESS = "DELETE_PASSWORD_SUCCESS";
export const DELETE_PASSWORD_FAILED = "DELETE_PASSWORD_FAILED";

export const ADD_PASSWORD_REQUEST = "ADD_PASSWORD_REQUEST";
export const ADD_PASSWORD_SUCCESS = "ADD_PASSWORD_SUCCESS";
export const ADD_PASSWORD_FAILED = "ADD_PASSWORD_FAILED";

// Secure Notes
export const SECURE_NOTE_REQUEST = "SECURE_NOTE_REQUEST";
export const SECURE_NOTE_SUCCESS = "SECURE_NOTE_SUCCESS";
export const SECURE_NOTE_FAILED = "SECURE_NOTE_FAILED";

export const SINGLE_SECURE_NOTE_REQUEST = "SINGLE_SECURE_NOTE_REQUEST";
export const SINGLE_SECURE_NOTE_SUCCESS = "SINGLE_SECURE_NOTE_SUCCESS";
export const SINGLE_SECURE_NOTE_FAILED = "SINGLE_SECURE_NOTE_FAILED";

export const ADD_SECURE_NOTE_REQUEST = "ADD_SECURE_NOTE_REQUEST";
export const ADD_SECURE_NOTE_SUCCESS = "ADD_SECURE_NOTE_SUCCESS";
export const ADD_SECURE_NOTE_FAILED = "ADD_SECURE_NOTE_FAILED";

export const EDIT_SECURE_NOTE_REQUEST = "EDIT_SECURE_NOTE_REQUEST";
export const EDIT_SECURE_NOTE_SUCCESS = "EDIT_SECURE_NOTE_SUCCESS";
export const EDIT_SECURE_NOTE_FAILED = "EDIT_SECURE_NOTE_FAILED";

export const DELETE_SECURE_NOTE_REQUEST = "DELETE_SECURE_NOTE_REQUEST";
export const DELETE_SECURE_NOTE_SUCCESS = "DELETE_SECURE_NOTE_SUCCESS";
export const DELETE_SECURE_NOTE_FAILED = "DELETE_SECURE_NOTE_FAILED";

// Categories
export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_FAILED = "CATEGORIES_FAILED";

export const ADD_CATEGORIES_REQUEST = "ADD_CATEGORIES_REQUEST";
export const ADD_CATEGORIES_SUCCESS = "ADD_CATEGORIES_SUCCESS";
export const ADD_CATEGORIES_FAILED = "ADD_CATEGORIES_FAILED";
